#include <cmath>
#include "../_c_cpp_langwork_.h"

struct Student
{
    std::string student_name;
    float hoursStudied;
    float attendance;
    int assignmentsCompleted;
    int passed;
};

std::vector<Student> student_dataset__ =
{
    {"jahnvi chaudhary", 1.5f, 62.0f, 1, 0},
    {"anshi chaudhary", 2.0f, 25.0f, 2, 0},
    {"yash dhiman", 3.0f, 13.0f, 3, 0},
    {"savita singh", 0.5f, 38.0f, 0, 0},
    {"vansh pathak", 4.0f, 68.0f, 5, 1},
    {"sumit tyagi", 4.5f, 82.0f, 7, 1},
    {"shivam shriwas", 5.0f, 79.0f, 6, 1},
    {"vanshi pawariya", 5.5f, 90.0f, 8, 1},
    {"tanya solanki", 6.0f, 95.0f, 9, 1},
    {"kartik aggarwal", 7.0f, 88.0f, 8, 1},
    {"Anshu naagar", 6.0f, 97.0f, 9, 1}, // High attendance & assignments compensate
    {"garuav vishawakarma", 6.5f, 45.0f, 2, 0}, // Studies a lot but skips classes & assignments
    {"lalit boob", 3.5f, 72.0f, 5, 1},
    {"Jatin panwari", 2.0f, 81.0f, 7, 1},
    {"palwinder singh", 4.5f, 50.0f, 3, 0},
    {"Gaurav taneja", 7.5f, 97.0f,10, 1},
    {"Vedanshi akku", 2.5f, 75.0f, 6, 0},
    {"Prachi shekhar", 5.0f, 65.0f, 4, 1},
    {"Mayank goel", 3.0f, 48.0f, 2, 0},
    {"Natik sahani", 6.0f, 84.0f, 7, 1}
};

const float average_bias___         = -2.0f;
const float weight_hours            = 0.8f;
const float weight_attendance       = 0.3f;
const float weight_assignments      = 0.6f;
const float ranking_cutoff___       = 0.313323f;


struct performer {
    std::string performer_name;
    float predictive_score;
};
class _neuron_algo_instruction__ {
public:
    static float _sigmoid_probability(float score) {
        return 1.0f / (1.0f + std::exp(-score));
    } static std::vector<performer> _forward_pass__() {
        std::vector<performer> predictions;
        for(unsigned int i = 0; i < student_dataset__.size(); i++){
            float summative_score =
                ((student_dataset__[i].hoursStudied   /8.0f)     * weight_hours)
              + ((student_dataset__[i].attendance /100.0f   )       * weight_attendance)
              + ((student_dataset__[i].assignmentsCompleted /10.0f) * weight_assignments)
              + average_bias___;
            float probability =
                _sigmoid_probability(summative_score);
            predictions.push_back({
                student_dataset__[i].student_name,
                probability
            });
        }
        return predictions;
    }
    static void _make_decisions(
        const std::vector<performer>& predictions) {
        std::cout << "\n========== Selected Performers ==========\n\n";
        for(const auto& student : predictions) {
            if(student.predictive_score >= ranking_cutoff___) {
                std::cout
                    << student.performer_name
                    << " -> "
                    << student.predictive_score
                    << '\n';
            } std::this_thread::sleep_for(std::chrono::seconds(1));

        }
    }
    static void _display_predictions(
        const std::vector<performer>& predictions) {
        std::cout << "\n========== All Predictions ==========\n\n";
        for(const auto& student : predictions) {
            std::cout
                << student.performer_name
                << " : "
                << student.predictive_score
                << '\n';
        }
    }
};

static int selection_binary_run__(int argc, const char *argv[])
{
    std::vector<performer> predictions =
        _neuron_algo_instruction__::_forward_pass__();
    _neuron_algo_instruction__::_display_predictions(predictions);
    _neuron_algo_instruction__::_make_decisions(predictions);
    return 0;
}

/*
-- sample data used; 
Data generated by ChatGPT
a basic example absolute starting point implementation of logistic regression classifier
: #pragma once
#include <vector>
#include <string>

struct Student
{
    std::string student_name;
    float hoursStudied;
    float attendance;
    int assignmentsCompleted;
    int passed;
};

std::vector<Student> student_dataset__ =
{
    {"jahnvi chaudhary", 1.5f, 62.0f, 1, 0},
    {"anshi chaudhary", 2.0f, 25.0f, 2, 0},
    {"yash dhiman", 3.0f, 13.0f, 3, 0},
    {"savita singh", 0.5f, 38.0f, 0, 0},
    {"vansh pathak", 4.0f, 68.0f, 5, 1},
    {"sumit tyagi", 4.5f, 82.0f, 7, 1},
    {"shivam shriwas", 5.0f, 79.0f, 6, 1},
    {"vanshi pawariya", 5.5f, 90.0f, 8, 1},
    {"tanya solanki", 6.0f, 95.0f, 9, 1},
    {"kartik aggarwal", 7.0f, 88.0f, 8, 1},
    {"Anshu naagar", 6.0f, 97.0f, 9, 1}, // High attendance & assignments compensate
    {"garuav vishawakarma", 6.5f, 45.0f, 2, 0}, // Studies a lot but skips classes & assignments
    {"lalit boob", 3.5f, 72.0f, 5, 1},
    {"Jatin panwari", 2.0f, 81.0f, 7, 1},
    {"palwinder singh", 4.5f, 50.0f, 3, 0},
    {"Gaurav taneja", 7.5f, 97.0f,10, 1},
    {"Vedanshi akku", 2.5f, 75.0f, 6, 0},
    {"Prachi shekhar", 5.0f, 65.0f, 4, 1},
    {"Mayank goel", 3.0f, 48.0f, 2, 0},
    {"Natik sahani", 6.0f, 84.0f, 7, 1}
};
*/


/*
output : ~~~
 --- /workspaces/codespaces-blank/build/main
@anxdydx ➜ /workspaces/codespaces-blank/build $ /workspaces/codespaces-blank/build/main

========== All Predictions ==========

jahnvi chaudhary : 0.167423
anshi chaudhary : 0.167284
yash dhiman : 0.185276
savita singh : 0.137525
vansh pathak : 0.25049
sumit tyagi : 0.29235
shivam shriwas : 0.288434
vanshi pawariya : 0.331812
tanya solanki : 0.360084
kartik aggarwal : 0.364473
Anshu naagar : 0.361468
garuav vishawakarma : 0.250678
lalit boob : 0.243424
Jatin panwari : 0.242872
palwinder singh : 0.227936
Gaurav taneja : 0.411202
Vedanshi akku : 0.23776
Prachi shekhar : 0.256355
Mayank goel : 0.192166
Natik sahani : 0.325634

========== Selected Performers ==========

vanshi pawariya -> 0.331812
tanya solanki -> 0.360084
kartik aggarwal -> 0.364473
Anshu naagar -> 0.361468
Gaurav taneja -> 0.411202
Natik sahani -> 0.325634
@anxdydx ➜ /workspaces/codespaces-blank/build $ /workspaces/codespaces-blank/build/main

========== All Predictions ==========

jahnvi chaudhary : 0.167423
anshi chaudhary : 0.167284
yash dhiman : 0.185276
savita singh : 0.137525
vansh pathak : 0.25049
sumit tyagi : 0.29235
shivam shriwas : 0.288434
vanshi pawariya : 0.331812
tanya solanki : 0.360084
kartik aggarwal : 0.364473
Anshu naagar : 0.361468
garuav vishawakarma : 0.250678
lalit boob : 0.243424
Jatin panwari : 0.242872
palwinder singh : 0.227936
Gaurav taneja : 0.411202
Vedanshi akku : 0.23776
Prachi shekhar : 0.256355
Mayank goel : 0.192166
Natik sahani : 0.325634

========== Selected Performers ==========

vanshi pawariya -> 0.331812
tanya solanki -> 0.360084
kartik aggarwal -> 0.364473
Anshu naagar -> 0.361468
Gaurav taneja -> 0.411202
Natik sahani -> 0.325634
@anxdydx ➜ /workspaces/codespaces-blank/build $ ^C
@anxdydx ➜ /workspaces/codespaces-blank/build $ 
*/
